### ISSUE TITLE
Causes vim to freeze

### ISSUE THREAD

**Issue by Jab2870** [ardagnir/united-front#4]
Hi,

I have got the most recent version of united-front installed using pathogen. It has worked flawlessly for many months.

Unfortunately, vim freezes when I try and open it and I have to use `CTRL` + `c` to get out.

I have tried deleting the `~/.unitedfront` file with no luck. Disabling the plugin fixes the problem.

**Comment by ardagnir** [comment]
Did it start happening when you updated vim? What version of vim and operating system are you using?

**Comment by Jab2870** [comment]
I am using Vim 8.0 on Arch Linux with kernel 4.13.3-1.

```
$ uname -a
Linux jonathansnuc 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
$ vim --version | head -n 3
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 28 2017 23:16:46)
Included patches: 1-1159
Compiled by Arch Linux
```

**Comment by ardagnir** [comment]
It looks like,occasionally, remote_expr can hang in new vim versions in a way that's hard to reproduce. I added a timeout that should fix this, but since I can't reproduce the problem reliably, it's hard to know for sure.

**Comment by ardagnir** [comment]
It looks like,occasionally, remote_expr can hang in new vim versions in a way that's hard to reproduce. I added a timeout that should fix this, but since I can't reproduce the problem reliably, it's hard to know for sure.
